export const homePageConstants = {
    SET_SCROLL_FLAG: 'SET_SCROLL_FLAG',

    GET_HERO_PHOTO_REQUEST: 'GET_HERO_PHOTO_REQUEST',
    GET_HERO_PHOTO_SUCCESS: 'GET_HERO_PHOTO_SUCCESS',
    GET_HERO_PHOTO_FAILURE: 'GET_HERO_PHOTO_FAILURE',

    GET_TAGS: 'GET_TAGS'
}