export const searchPageConstants = {
    GET_SEARCH_PHOTOS_REQUEST: 'GET_SEARCH_PHOTOS_REQUEST',
    GET_SEARCH_PHOTOS_SUCCESS: 'GET_SEARCH_PHOTOS_SUCCESS',
    GET_SEARCH_PHOTOS_FAILURE: 'GET_SEARCH_PHOTOS_FAILURE'
}